title: Sean Chiang - Quantitative Finance Student
description: Passionate about applying machine learning and data science to discover investment opportunities and develop risk management strategies. Currently studying Computational Finance at City University of Hong Kong.
author: Sean Chiang
profile_image: /assets/images/sean_chiang_profile.jpg
email: sean.chiang@example.com
linkedin: https://linkedin.com/in/seanchiang
github: https://github.com/seanchiang
resume: /assets/documents/sean_chiang_resume.pdf
